package Part1;

import java.io.IOException;

//public class Trycatch {

//	public static void main(String[] args) {
//		int i=2;
//		int j=0;
		
//		try {
//			int k=i/j;
//		}
//		catch(ArithmeticException e) {
//			System.out.println("j can not be zero");
			
//		}

//	}

//}


/*	public class Trycatch {
	
		public static void main(String[] args) throws IOException {
			int i=2;
			int j=0;
			
			try {
				int k=i/j;
			}
			catch(ArithmeticException e) {
				System.out.println("j can not be zero");
				
			}
		}
	
	}
*/



/*
 * public class Trycatch {
 * 
 * public static void main(String[] args) { int i=2; int j=0;
 * 
 * try { int k=i/j; } catch(ArithmeticException e) {
 * System.out.println("j can not be zero");
 * 
 * }
 * 
 * finally { System.out.println("finally bye"); } }
 * 
 * }
 */





/*
 * public class Trycatch {
 * 
 * public static void main(String[] args) { int i=2; int j=0;
 * 
 * try { int k=i/j; } catch(ArithmeticException e) {
 * System.out.println("j can not be zero");
 * 
 * } catch(Exception e) { System.out.println("unexpected exception");
 * 
 * } }
 * 
 * }
 */



